---
engines:
  rubocop:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.scss"
exclude_paths:
- node_modules/**/*
- test/**/*
- karma.conf.js
